name: Hello
on: 
  push:
    branches:
      - CI_Hello
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: HelloWorld
        run: echo ${{ secrets.GITHUB_TOKEN }}
#        uses: action/checkout@v3