name: Hello
env:
  project_key: "mcyazvat_SomethingCoolStuff"
  api_url: "https://sonarcloud.io/api/qualitygates/project_status"
on: 
  push:
    branches:
      - CD
jobs:
  CD:
    name: createImageNginx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: createImage
        run: |
          pwd
          ls -l
          echo 'FROM nginx
          COPY ./front/index.html /usr/share/nginx/html/index.html' > dockerfile
          ls -l
          cat dockerfile
          docker build -t scsnginx:latest .
          ls -l
          docker images
          docker save scsnginx:latest > scsnginx_latest.tar
          ls -l
      - name: Delivery
        env: 
          SSH_TO_SCS: ${{ secrets.SSH_TO_SCS }}
        run: |
          mkdir -p /home/runner/.ssh 
          echo "$SSH_TO_SCS" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -v -i /home/runner/.ssh/id_rsa /home/runner/work/SomethingCoolStuff/SomethingCoolStuff/scsnginx_latest.tar scstuff@83.172.42.34:/scs/
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: CD
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: SonarCloud_Status
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          sonar_response=$(curl -s "${api_url}?projectKey=${project_key}&branch=${branch_name}")
          status=$(echo $sonar_response | jq -r '.projectStatus.status')
          if [ "$status" = "OK" ] || [ "$status" = "WARN" ] ; then
            echo "Analysis completed successfully."
            echo "https://sonarcloud.io/summary/new_code?id=${project_key}&branch=${branch_name}"
          else
            echo "Analysis failed or status is not successful."
            echo "https://sonarcloud.io/summary/new_code?id=${project_key}&branch=${branch_name}"
            exit 1
          fi
